### PR TITLE
WIP: Website for template

### PR DESCRIPTION
**Pull request by mundane140**
Related to #26 

## To do 
- [x] A starter app using create-next-app
- [ ] Add basic layout using create-react-app website as a reference
- [ ] Add components as per content

### CODE REVIEW

File: website/pages/index.js [hunk 1]
```diff
@@ -0,0 +1,209 @@
+import Head from 'next/head'
+
+export default function Home() {
+  return (
+    <div className="container">
```
Comment (udaypydi) [inline website/pages/index.js:5]: I added tailwind to the project. It will be great if we can use that. Or have a look at [tail-ui](https://github.com/udaypydi/tail-ui). A react component library based on tailwind css

Comment (mundane140) [reply website/pages/index.js:5]: I don't have prior experience with TailwindCSS. I'll try to do what I can with this but you might have to take lead on this one.

Comment (udaypydi) [reply website/pages/index.js:5]: Sure. I will tae care of the styling and tail-ui components.

**Comment by mundane140** [comment]
@udaypydi This won't work unless we convert this repository into a monorepo.
Do you want me to do it?

**Comment by udaypydi** [comment]
> @udaypydi This probably won't work unless we convert this repository into a monorepo.
> Do you want me to do it?

Doesn't this work independently considering the `website` as the root folder. For now we aren't considering to use any of the configs from boilerplate.

**Comment by udaypydi** [comment]
> @udaypydi This probably won't work unless we convert this repository into a monorepo.
> Do you want me to do it?

monorepo is a good option, but I wanted to wrap up few things before going to this.

**Comment by mundane140** [comment]
When I initialize the next app in /website directory, I get this error:
`Error: Cannot find module 'tailwindcss'`
Here is the stacktrace:
`
Require stack:
- /home/nm/projects/github/react-simple-boilerplate/postcss.config.js
- /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/lib/find-config.js
- /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js
- /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/blocks/css/index.js
- /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/index.js
- /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack-config.js
- /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/hot-reloader.js
- /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/next-dev-server.js
- /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/next.js
- /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/lib/start-server.js
- /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/cli/next-dev.js
- /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/nm/projects/github/react-simple-boilerplate/postcss.config.js:1:21)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at findConfig (/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/lib/find-config.js:7:181)
    at async getPostCssPlugins (/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:4:141)
    at async __overrideCssConfiguration (/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/blocks/css/overrideCssConfiguration.js:1:272)
    at async getBaseWebpackConfig (/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack-config.js:119:120)
    at async Promise.all (index 0) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/nm/projects/github/react-simple-boilerplate/postcss.config.js',
    '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/lib/find-config.js',
    '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js',
    '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/blocks/css/index.js',
    '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/index.js',
    '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack-config.js',
    '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/hot-reloader.js',
    '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/next-dev-server.js',
    '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/next.js',
    '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/lib/start-server.js',
    '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/cli/next-dev.js',
    '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/bin/next'
  ]
`
The issue is not the missing package. The command should look for the tailwindcss module in the /website/node_modules and use it. But it's looking for the module in the root folder.

**Comment by udaypydi** [comment]
> When I initialize the next app in /website directory, I get this error:
> `Error: Cannot find module 'tailwindcss'`
> Command:
> `~/projects/github/react-simple-boilerplate/website$ yarn dev`
> results in:
> `
> yarn run v1.22.4
> $ next dev
> ready - started server on http://localhost:3000
> Error: Cannot find module 'tailwindcss'
> Require stack:
> 
> * /home/nm/projects/github/react-simple-boilerplate/postcss.config.js
> * /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/lib/find-config.js
> * /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js
> * /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/blocks/css/index.js
> * /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/index.js
> * /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack-config.js
> * /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/hot-reloader.js
> * /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/next-dev-server.js
> * /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/next.js
> * /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/lib/start-server.js
> * /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/cli/next-dev.js
> * /home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/bin/next
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:690:27)
>   at Module.require (internal/modules/cjs/loader.js:852:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at Object. (/home/nm/projects/github/react-simple-boilerplate/postcss.config.js:1:21)
>   at Module._compile (internal/modules/cjs/loader.js:959:30)
>   at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
>   at Module.load (internal/modules/cjs/loader.js:815:32)
>   at Function.Module._load (internal/modules/cjs/loader.js:727:14)
>   at Module.require (internal/modules/cjs/loader.js:852:19)
>   at require (internal/modules/cjs/helpers.js:74:18)
>   at findConfig (/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/lib/find-config.js:7:181)
>   at async getPostCssPlugins (/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js:4:141)
>   at async __overrideCssConfiguration (/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/blocks/css/overrideCssConfiguration.js:1:272)
>   at async getBaseWebpackConfig (/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack-config.js:119:120)
>   at async Promise.all (index 0) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>   '/home/nm/projects/github/react-simple-boilerplate/postcss.config.js',
>   '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/lib/find-config.js',
>   '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/blocks/css/plugins.js',
>   '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/blocks/css/index.js',
>   '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack/config/index.js',
>   '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/build/webpack-config.js',
>   '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/hot-reloader.js',
>   '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/next-dev-server.js',
>   '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/next.js',
>   '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/server/lib/start-server.js',
>   '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/cli/next-dev.js',
>   '/home/nm/projects/github/react-simple-boilerplate/website/node_modules/next/dist/bin/next'
>   ]
>   }
> 
> `
> The issue is not the missing package. The command should look for the tailwindcss module in the /website/node_modules and use it. But it's looking for the module in the root folder.
> 
> I am running `yarn dev` from `/website` directory.

Ah.. got it. I will merge this branch to an integration branch in the actual repo and then get it running,

**Comment by mundane140** [comment]
@udaypydi were you able to run the development server for website?
